apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{appName}}-production
resources:
- ../base
- config.yaml
- ingress.yaml
- namespace.yaml
- secret.yaml

images:
- name: {{imageName}}
  newTag: {{imageTagProd}}
