apiVersion: v1
kind: Service
metadata:
  name: {{serviceName}}
  labels:
    app: {{appName}}
spec:
  type: LoadBalancer
  selector:
    app: {{appName}}
  ports:
  - name: http
    port: 80
    targetPort: {{targetPort}}
